name: GitHub Actions Test
run-name: ${{ github.actor }} a lancé les tests sur PrivateBin 🚀
on:
  push:
  pull_request:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/phpstan@v3
        with:
          path: lib/
      - name: Essaie des tests
        uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: coverage
        with:
          php_extensions: gd xdebug
          configuration: ./phpunit.xml
          bootstrap: ./tst/Bootstrap.php
          version: 9
          php_version: 8.1

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server-dir: 'www/'
          exclude: "[**/.git/**, **/vendor/**]"
          server: ${{ secrets.URL }}
          username: ${{ secrets.LOGIN }}
          password: ${{ secrets.MDP_FTP }}
