name: PHP Actions
run-name: ${{ github.actor }} a lancé les tests sur PrivateBin 🚀
on:
  push:
  pull_request:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6

      - name: Essaie des tests
        uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: coverage
        with:
          php_extensions: gd xdebug
          configuration: ./phpunit.xml
          bootstrap: ./tst/Bootstrap.php
          version: 9
          php_version: 8.1

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: log/coverage-cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
        continue-on-error: true


      - name: PHP Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          php_version: 8.1
          path: lib/
          standard: PSR12
        continue-on-error: true

      - name: PHP Mess Detector
        uses: php-actions/phpmd@v1
        with:
          php_version: 8.1
          path: lib/
          output: text
          ruleset: cleancode
        continue-on-error: true

      - uses: php-actions/phpstan@v3
        with:
          path: lib/
          level: 9
        continue-on-error: true  

