name: GitHub Actions Test
run-name: ${{ github.actor }} a lancé les tests sur PrivateBin 🚀
on: 
  push:
  pull_request:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation de Composer
        uses: php-actions/composer@v6

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.url }}
          username: ${{ secrets.login }}
          password: ${{ secrets.mdp_fpt }}