name: GitHub Actions Test
run-name: ${{ github.actor }} a lancé les tests sur PrivateBin 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: cd PrivateBin-main/
      - run: make test
